import 'package:get/get.dart';

class MyLocale implements Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "Code enter": "ادخل الكود",
          "LOG IN": "تسجيل دخول",
          "Phone": "رقم الهاتف",
          "password": "كلمة المرور",
          "Continue as": "الدخول بصفة",
          "a Guest": "ضيف",
          "Don't have an account ?": "ليس لديك حساب ؟",
          "Sign Up": "انشاء حساب",
          "PHONE MUST BE REQUIRED": "يرجى ادخال رقم الهاتف",
          "PASSWORD MUST BE REQUIRED": "يرجى ادخال كلمة المرور",
          "Account not found": "الحساب غير موجود",
          "Make sure the data is correct": "تأكد من صحة البيانات",
          "Create an Account": "انشاء حساب",
          "First Name": "الاسم الاول",
          "Middle Name": "الاسم الثاني",
          "Last Name": "الاسم الاخير",
          "Password confirmation": "تأكيد كلمة المرور",
          "Email": "الايميل",
          "Governorate": "المحافظة",
          "Address": "العنوان",
          "Specializations": "التخصص",
          "Universities": "الجامعة",
          "Are you graduated ?": "هل انت خريج ؟",
          "NO": "لا",
          "YES": "نعم",
          "Year": "السنة",
          "The password must be at least 8 characters":
              "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل",
          "password does not match": "كلمة المرور غير متطابقة",
          "Done!": "تم",
          "My Courses": "كورساتي",
          "There are no courses to display": "لايوجد دورات لعرضها",
          "You do not have a subscription to any course":
              "ليس لديك اشتراك في أي دورة",
          "Subscribe to a course": "اشترك بكورس",
          "hour": "ساعة",
          "Chapter": "فصل",
          "Comments": "تعليقات",
          "Ratings": "تقييمات",
          "Chapters": "الفصول",
          "Teachers": "المدرسيين",
          "There are no data": "لاتوجد بيانات لعرضها",
          "Course request": "اطلب الكورس",
          "Subscription completed successfully": "تم الاشتراك بنجاح",
          "Please try again later": "يرجى المحاولة لاحقاً",
          "Sessions": "الجلسات",
          "Files": "ملفات",
          "Exams": "اختبارات",
          "Complaint sent successfully": "تم تقديم الطلب بنجاح",
          "Click to download the book": "اضغط هنا لتحميل الكتاب",
          "time is over": "انتهى الوقت",
          "Time has expired. Please try again later":
              "انتهى الوقت. الرجاء معاودة المحاولة في وقت لاحق",
          "Finish": "انهاء",
          "  seconds": "ثانية",
          "test duration :  ": "مدة الاختبار :  ",
          "description": "التفاصيل:",
          "Start": "ابداء",
          "minutes": "دقائق",
          "test duration": "مدة الاختبار",
          "Home": "الرئيسية",
          "Language": "اللغة",
          "Contact us": "تواصل معنا",
          "There is no subscription": "لايوجد اشتراك",
          "Please sign up for the course first":
              "الرجاء التسجيل في الدورة أولا",
          "Complaints": "الشكاوي",
          "Enter the complaint": "ادخل الشكوى",
          "Profile": "الحساب الشخصي",
          "You do not have an account": "لا يوجد لديك حساب",
          "Please create an account": "الرجاء إنشاء حساب",
          "Please send a copy of the payment receipt":
              "يرجى ارسال صورة وصل الدفع",
          "Add image": "اضافة صورة",
          " sp": " ل.س ",
          "Please select a payment process": "الرجاء تحديد عملية الدفع",
          "Bank": "بنك",
          "Coupon": "كوبون",
          "Enter the comments": "اكتب تعليقك",
          "Upload completed": "اكتمل التحميل",
          "The verification code has been sent successfully":
              "تم إرسال رمز التحقق بنجاح",
          "Code": "يرجى ادخال الكود",
          "Code activation": "تفعيل الكود",
          "The code is incorrect": "الكود غير صحيح",
          "Terms and Conditions": "الشروط والاحكام",
          "Do you agree": "هل توافق على "
        },
        "en": {
          "Terms and Conditions": "Terms and Conditions ",
          "Do you agree": "Do you agree ",
          "Code enter": "Enter the code",
          "The code is incorrect": "The code is incorrect",
          "Code activation": "Code activation",
          "code": "Please enter the code",
          "The verification code has been sent successfully":
              "The verification code has been sent successfully",
          "SIGN IN": "SIGN IN",
          "Phone": "Phone",
          "password": "password",
          "Continue as": "Continue as",
          "a Guest": "a Guest",
          "Don't have an account ?": "Don't have an account ?",
          "Sign Up": "Sign Up",
          "PHONE MUST BE REQUIRED": "PHONE MUST BE REQUIRED",
          "PASSWORD MUST BE REQUIRED": "PASSWORD MUST BE REQUIRED",
          "Account not found": "Account not found",
          "Make sure the data is correct": "Make sure the data is correct",
          "Create an Account": "Create an Account",
          "First Name": "First Name",
          "Middle Name": "Middle Name",
          "Last Name": "Last Name",
          "Password confirmation": "Password confirmation",
          "Email": "Email",
          "Governorate": "Governorate",
          "Address": "Address",
          "Specializations": "Specializations",
          "Universities": "Universities",
          "Are you graduated ?": "Are you graduated ?",
          "NO": "NO",
          "YES": "YES",
          "Year": "Year",
          "The password must be at least 8 characters":
              "The password must be at least 8 characters",
          "password does not match": "password does not match",
          "Done!": "Done!",
          "My Courses": "My Courses",
          "There are no courses to display": "There are no courses to display",
          "You do not have a subscription to any course":
              "You do not have a subscription to any course",
          "Subscribe to a course": "Subscribe to a course",
          "hour": "hour",
          "Chapter": "Chapter",
          "Comments": "Comments",
          "Ratings": "Ratings",
          "Chapters": "Chapters",
          "Teachers": "Teachers",
          "There are no data": "There are no data",
          "Course request": "Course request",
          "Subscription completed successfully":
              "Subscription completed successfully",
          "Please try again later": "Please try again later",
          "Sessions": "Sessions",
          "Files": "Files",
          "Exams": "Exams",
          "Complaint sent successfully":
              "The request has been submitted successfully",
          "Click to download the book": "Click to download the book",
          "time is over": "time is over",
          "Time has expired. Please try again later":
              "Time has expired. Please try again later",
          "Finish": "Finish",
          "  seconds": "  seconds",
          "test duration :  ": "test duration :  ",
          "description": "description:",
          "Start": "Start",
          "minutes": "minutes",
          "test duration": "test duration",
          "Home": "Home",
          "Language": "Language",
          "Contact us": "Contact us",
          "There is no subscription": "There is no subscription",
          "Please sign up for the course first":
              "Please sign up for the course first",
          "Complaints": "Complaints",
          "Enter the complaint": "Enter the complaint",
          "Profile": "Profile",
          "You do not have an account": "You do not have an account",
          "Please create an account": "Please create an account",
          "Please send a copy of the payment receipt":
              "Please send a copy of the payment receipt",
          "Add image": "Add image",
          " sp": " sp",
          "Please select a payment process": "Please select a payment process",
          "Bank": "Bank",
          "Coupon": "Coupon",
          "Enter the comments": "Enter the Comments",
          "Upload completed": "Upload completed"
        },
      };
}
